#!/usr/bin/env bash
#-----------------------------------------------------------#
# @author: demmonico, @email demmonico@gmail.com, @repo https://github.com/demmonico/terra-compose, ©2021-2023
#-----------------------------------------------------------#

read -r -d '' HELP_STRING <<'EOF'
-----------------------------------------------------------
Help information
-----------------------------------------------------------
TerraCompose is a tool aimed to help to run Terraform commands in Docker and protect you against changes wrongly.

FORMAT: <SCRIPT_NAME> <ACTION> <ALIAS>

<ACTION> - TF action you want to run:
    - plan
    - apply
    - workspaces    - equal to `workspace list`
    - run           - proxy all arguments directly to `terraform`. 
                      Allows running any custom command
    - shell         - run a shell inside the terraform docker container.
                      Allows running any custom commands inside
    - help          - this help information
<ALIAS>  - a unique shortcut to project/environment pair, like `runner_prod`.

EOF

set -e

RC='\033[0;31m'
YC='\033[0;33m'
NC='\033[0m' # No Color

VERBOSE_DEBUG_MODE=0
VERBOSE_INFO_MODE=1
VERBOSE_ERROR_MODE=2
VERBOSE_MODE="${VERBOSE_INFO_MODE}" # default

_DIR="$(pwd)"
BASE_DIR="${_DIR}"
CONFIG_YAML_FILE="${_DIR}/aliases.yaml"
TF_PLAN_FILENAME='plan.tfplan'

HELP_STRING="${HELP_STRING}$( echo -e "\n\nList of available aliases from ${YC}${CONFIG_YAML_FILE}${NC}:\n>>>>>"; cat ${CONFIG_YAML_FILE} | grep -v -E "^$|^\s*\#"; echo "<<<<<" )"

is_debug_verbose_mode() {
    [[ "${VERBOSE_MODE}" -le "${VERBOSE_DEBUG_MODE}" ]]
}

initProject() {
    local PROJECT_SUBPATH="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'path' )"
    if [ -z "${PROJECT_SUBPATH}" ]; then
        echo -e "${RC}Error${NC}: no path was found for alias ${YC}${ALIAS}${NC}"
        exit 2
    fi
    PROJECT_DIR="${BASE_DIR}/${PROJECT_SUBPATH}"
    if [ -z "${PROJECT_DIR}" ] || [ ! -d "${PROJECT_DIR}" ]; then
        echo -e "${RC}Error${NC}: empty project DIR or was found for alias ${YC}${ALIAS}${NC}"
        exit 2
    fi

    PROJECT_WORKSPACE="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'workspace' )"
    PROJECT_TFVAR="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'tfvars' )"

    TF_PLAN_FILE="${PROJECT_DIR}/${TF_PLAN_FILENAME}"

    local TF_DEFAULT_VERSION="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'default' 'tfversion' )"
    local TF_PROJECT_VERSION="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'tfversion' )"
    TF_VERSION="${TF_PROJECT_VERSION:-${TF_DEFAULT_VERSION}}"

    PROJECT_BACKEND_CONFIG="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'backend_config' )"

    PROJECT_HOOK_BEFORE_TF_INIT="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'hooks' 'before_tf_init' )"
    PROJECT_HOOK_AFTER_TF_INIT="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'hooks' 'after_tf_init' )"
    PROJECT_HOOK_BEFORE_ACTION="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'hooks' 'before_action' )"
    PROJECT_HOOK_AFTER_ACTION="$( getYamlConfigValue ${CONFIG_YAML_FILE} 'aliases' "${ALIAS}" 'hooks' 'after_action' )"

    # env vars file
    ENV_VARS_FILE_DOCKER_PARAM=''
    if [ -f .env ]; then
      ENV_VARS_FILE_DOCKER_PARAM="--env-file ${BASE_DIR}/.env"
    fi
}

runTerraform() {
    local cmd=$@

    if is_debug_verbose_mode; then
        echo -e "${YC} >>> Command: ${RC}"
        # prevent to expand the color on the subshell when spinning up the interactive shell
        if [ -z "${args}" ]; then
            echo -n -e "${NC}"
        fi
        set -x
    fi

    docker run --rm -ti \
        -v "${BASE_DIR}":"${BASE_DIR}" \
        -v ~/.aws:/root/.aws \
        -v ~/.ssh:/root/.ssh \
        -e AWS_PROFILE=${AWS_PROFILE} \
        ${ENV_VARS_FILE_DOCKER_PARAM} \
        -w=${PROJECT_DIR} \
        --entrypoint /bin/sh \
        hashicorp/terraform:${TF_VERSION} \
        ${cmd:+-c} ${cmd:+"${cmd}"}

    { if is_debug_verbose_mode; then
        set +x;
        echo -e "${NC}"
    fi } 2>/dev/null

}

runTerraformInit() {
    if [ -n "${PROJECT_HOOK_BEFORE_TF_INIT}" ]; then
        echo -e "${YC} >>> Running hook before init ... ${NC}"
        bash -c "${PROJECT_HOOK_BEFORE_TF_INIT}"
        echo -e "${YC} >>> Done ${NC}"
    fi

    local backend_config="${PROJECT_BACKEND_CONFIG:+"-backend-config=\"${PROJECT_BACKEND_CONFIG}\""}"
    cd "${PROJECT_DIR}" && \
        echo -e "Project dir is ${YC}${PROJECT_DIR}${NC} and we are currently right here!" && echo "" && \
        echo -e "${YC} >>> Running TF init${PROJECT_BACKEND_CONFIG:+" using '${backend_config}'"} ...${NC}" && \
        runTerraform terraform init ${backend_config}

    if [ -n "${PROJECT_HOOK_AFTER_TF_INIT}" ]; then
        echo -e "${YC} >>> Running hook after init ... ${NC}"
        bash -c "${PROJECT_HOOK_AFTER_TF_INIT}"
        echo -e "${YC} >>> Done ${NC}"
    fi
}

askWorkspace() {
    read -p "Please input workspace name: " CURRENT_WORKSPACE
    if [ -z "$( listWorkspaces | grep -E "${CURRENT_WORKSPACE}" )" ]; then
        echo -e "${RC}Error${NC}: Ooops, wrong workspace name ${YC}${CURRENT_WORKSPACE}${NC}. Please try again!" >&2
        askWorkspace
    fi
}

listWorkspaces() {
    runTerraform terraform workspace list
}

printListWorkspaces() {
    echo -e "\nTF workspaces:"
    listWorkspaces
}

selectWorkspace() {
    if [ -n "${PROJECT_WORKSPACE}" ]; then
        echo -e "${YC} >>> Workspace '${RC}${PROJECT_WORKSPACE}${YC}' was found in config${NC}"
        CURRENT_WORKSPACE="${PROJECT_WORKSPACE}"
    else
        echo -e -n "${YC} >>> Detecting TF workspaces ... ${NC}"
        local COUNT_OF_WORKSPACES="$( listWorkspaces | grep -v -e '^\s*$' | wc -l )"
        echo "${COUNT_OF_WORKSPACES} was detected"
        CURRENT_WORKSPACE="$( listWorkspaces | grep '*' | tr -dc '[:alnum:]' | cut -d " " -f2 )"

        if [ $COUNT_OF_WORKSPACES -gt 1 ] || [ ! "${CURRENT_WORKSPACE}" = "default" ]; then
            printListWorkspaces
            askWorkspace
        fi
    fi

    echo -e "${YC} >>> Selecting TF workspace ${RC}${CURRENT_WORKSPACE}${YC} ... ${NC}"
    runTerraform terraform workspace select ${CURRENT_WORKSPACE}
}

normalizeTfVarsFilename() {
    local FILENAME=$1
    if [[ "${FILENAME}" = *.tfvars ]] || [[ "${FILENAME}" = *.tfvars.json ]] || [[ "${FILENAME}" = *.tfvars.hcl ]]; then
        echo "${FILENAME}"
    else
        echo "${FILENAME}.tfvars"
    fi
}

askIfNotExistsTfVarsFile() {
    local FILENAME="$( normalizeTfVarsFilename "$1" )"
    local FILE="${PROJECT_DIR}/${FILENAME}"

    if [ -f "${FILE}" ]; then
        echo "${FILENAME}"
    else
        echo -e "Oops, file ${RC}${FILENAME}${NC} was not found at ${YC}${PROJECT_DIR}${NC} folder!" >&2
        echo -e "There are ${YC}*.tfvars${NC} files:" >&2
        eval "ls ${PROJECT_DIR} | grep --color '.tfvars'" >&2

        read -p "Please input filename (with or without .tfvars extension) which one you want to work with: " FILENAME
        echo "$( askIfNotExistsTfVarsFile "${FILENAME}" )"
    fi
}

humanTimeSinceFileModified() {
    local FILE=$1
    local TIME=$(( $(date +%s) - $(stat -f%c "${FILE}") ))
    local SECONDS=$((TIME%60))
    local MINUTES=$((TIME/60%60))
    local HOURS=$((TIME/60/60%24))
    local DAYS=$((TIME/60/60/24))
    (( $DAYS > 0 )) && printf '%d days ' $DAYS
    (( $HOURS > 0 )) && printf '%d hours ' $HOURS
    (( $MINUTES > 0 )) && printf '%d minutes ' $MINUTES
    (( $DAYS > 0 || $HOURS > 0 || $MINUTES > 0 )) && printf 'and '
    printf '%d seconds\n' $SECONDS
}

# See @package: https://github.com/demmonico/bash-parse-yaml
# get config value from yaml config
# format: getYamlConfigValue YAML_FILE_NAME parent1 patent2 ... config_key_name
function getYamlConfigValue {
  if [ "$#" -lt 2 ]; then
    echo -e "${RC}Error:${NC} too few arguments at '${YC}getYamlConfigValue${NC}'"
    exit 1
  fi

  local PREFIX='' CONFIG_YAML_FILE=$1

  local CONFIG_PATH="${PREFIX}"
  for i in "${@:2}"; do
    [ -z "${CONFIG_PATH}" ] && CONFIG_PATH="${i}" || CONFIG_PATH="${CONFIG_PATH}_${i}"
  done

  local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
  # shorter version from https://stackoverflow.com/a/21189044
  sed -ne "s|^\($s\):|\1|" \
      -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
      -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
  # compose list of variables like parent1_parent2_target="target value"
  awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) { if (i > indent) { delete vname[i]; idx[i]=0 } };
      if (length($2) == 0) { vname[indent]= ++idx[indent] };
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) { vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'${PREFIX:+${PREFIX}_}'", vn, vname[indent], $3);
      }
   }' |\
  # filter using pattern
  grep ${CONFIG_PATH} | \
  # fetch string value or list values
  {
    local RESULT
    declare -a CONFIG_RESULTS=()
    while read line; do CONFIG_RESULTS+=("${line}"); done

    # list value
    if [[ "${#CONFIG_RESULTS[*]}" -gt 1 ]]; then
      local CONFIG_VALUES=''
      for i in "${CONFIG_RESULTS[@]}"; do
        CONFIG_KEY="$( echo "${i}" | sed -E 's/^'"${CONFIG_PATH}_"'(.*)=.*$/\1/g' )"
        # validate key should be like ${CONFIG_PATH}_<number>
        if ! [[ ${CONFIG_KEY} =~ ^[0-9]+$ ]]; then
          echo -e "${RC}Error:${NC} config path '${YC}${CONFIG_PATH}${NC}' contains non-supported value (string or list)"
          exit 1
        fi
        # collect value
        if [ -z "${CONFIG_VALUES}" ]; then
          CONFIG_VALUES="$( echo "${i}" | sed -E 's/^.*"(.*)".*$/\1/g' )"
        else
          CONFIG_VALUES="${CONFIG_VALUES}"$'\n'"$( echo "${i}" | sed -E 's/^.*"(.*)".*$/\1/g' )"
        fi
      done
      RESULT="${CONFIG_VALUES}"

    # single value
    else
      RESULT=$( echo "${CONFIG_RESULTS[@]}" | sed -E 's/^.*"(.*)".*$/\1/g' )
    fi

    echo "${RESULT}"
  }
}

#-----------------------------------------------------------#

ACTION=$1
case "${ACTION}" in
    'plan' | 'plan-debug' | 'apply' | 'apply-debug' | 'workspaces' | 'run' | 'shell' )
        ;;
    'help')
        echo "${HELP_STRING}"
        exit;;
    '')
        echo -e "${RC}Error${NC}: ACTION param is required"
        echo "${HELP_STRING}"
        exit 1;;
    *)
        echo -e "${RC}Error:${NC} invalid action ${ACTION}"
        echo "${HELP_STRING}"
        exit 1;;
esac

ALIAS=$2
if [ -z "${ALIAS}" ]; then
    echo -e "${RC}Error${NC}: ALIAS param is required"
    echo -e "${HELP_STRING}"
    exit 1
fi

initProject

#-----------------------------------------------------------#
##### Main
#-----------------------------------------------------------#

# check AWS access
AWS_PROFILE="${AWS_PROFILE:-"${AWS_DEFAULT_PROFILE}"}"
if [ -z "${AWS_PROFILE}" ]; then
    echo -e "${RC}Error${NC}: env var AWS_PROFILE/AWS_DEFAULT_PROFILE is empty. It's required to have one of them, pointing to the actual AWS profile (`~/.aws/credentials`)"
    exit 5
fi

if [ -n "${PROJECT_HOOK_BEFORE_ACTION}" ]; then
    echo -e "${YC} >>> Running hook before action ... ${NC}"
    bash -c "${PROJECT_HOOK_BEFORE_ACTION}"
    echo -e "${YC} >>> Done ${NC}"
fi

# TF action
case "${ACTION}" in
    # use the latest workspace
    'run')
        echo -e "${YC} >>> Running custom command ${RC}terraform ${@:3}${NC} at the alias ${YC}${ALIAS} (${PROJECT_DIR})${NC}."
        echo -e "${YC} >>> ${RC}Please, be carefull!!!${NC}"
        read -p "Are you sure to proceed? To approve print 'yes': " APPLY_APPROVE
        if [ ! "${APPLY_APPROVE}" = 'yes' ]; then
            echo -e "${YC} >>> Exiting ... ${NC}\n"
            exit 0
        fi

        runTerraform ${@:3}
        exit;;

    # use the latest workspace
    'shell')
        echo -e "${YC} >>> Shelling into the ${RC}terraform ${@:3}${NC} at the alias ${YC}${ALIAS} (${PROJECT_DIR})${NC}."
        echo -e "${YC} >>> ${RC}Please, be carefull!!!${NC}"
        read -p "Are you sure to proceed? To approve print 'yes': " APPLY_APPROVE
        if [ ! "${APPLY_APPROVE}" = 'yes' ]; then
            echo -e "${YC} >>> Exiting ... ${NC}\n"
            exit 0
        fi

        runTerraform
        exit;;

    'workspaces')
        echo -e "${YC} >>> Workspace '${RC}${PROJECT_WORKSPACE}${YC}' was found in alias config${NC}"
        echo -e "${YC} >>> Detecting TF workspaces ... ${NC}"
        printListWorkspaces
        exit;;
    
    'plan')
        runTerraformInit

        # TF workspaces
        selectWorkspace

        # TF validation
        echo -e "${YC} >>> Checking format and validating TF templates ... ${NC}"
        runTerraform terraform fmt --check=true -recursive -diff
        runTerraform terraform validate

        # TF tfvars
        echo -e "${YC} >>> Searching for ${RC}tfvars${YC} file ... ${NC}"
        if [ -z "${PROJECT_TFVAR}" ]; then
            # no pre-configured tfvars
            echo -e "${YC} >>> No TFVARS filename was found at the config, so will try current workspace '${RC}${CURRENT_WORKSPACE}${YC}' as a TFVARS name${NC}"
            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${CURRENT_WORKSPACE}" )"
            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}"
        elif [ "${PROJECT_TFVAR}" = '-' ]; then    
            # pre-configured to skip tfvars
            echo -e "${YC} >>> Skipping TFVARS because '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
            TFVARS_FILENAME="-"
            TFVARS_COMMAND_PARAM=""
        else
            # pre-configured tfvars
            echo -e "${YC} >>> TFVARS filename '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${PROJECT_TFVAR}" )"
            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}"
        fi

        # TF plan
        echo -e "\n------------------------------------------------------------------------\n"
        echo -e "${YC} >>> Building TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvars ${RC}${TFVARS_FILENAME}${NC}"
        echo -e "\n------------------------------------------------------------------------\n"
        runTerraform terraform plan ${TFVARS_COMMAND_PARAM} -out=${TF_PLAN_FILENAME}
        echo -e "\n${YC} >>> TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvars ${RC}${TFVARS_FILENAME}${NC}: was generated plan ${RC}${TF_PLAN_FILENAME}${NC}\n${YC} >>> ${NC}(${TF_PLAN_FILE})\n"
        exit;;

    # TODO re-use plan action
    'plan-debug')
        echo -e "${YC} >>> Running in ${RC}DEBUG${YC} mode (without init backend, format check and validation)!${NC}"
        echo -e "\n------------------------------------------------------------------------\n"

        # TF workspaces
        selectWorkspace

        # TF tfvars
        echo -e "${YC} >>> Searching for ${RC}tfvars${YC} file ... ${NC}"
        if [ -z "${PROJECT_TFVAR}" ]; then
            # no pre-configured tfvars
            echo -e "${YC} >>> No TFVARS filename was found at the config, so will try current workspace '${RC}${CURRENT_WORKSPACE}${YC}' as a TFVARS name${NC}"
            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${CURRENT_WORKSPACE}" )"
            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}"
        elif [ "${PROJECT_TFVAR}" = '-' ]; then
            # pre-configured to skip tfvars
            echo -e "${YC} >>> Skipping TFVARS because '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
            TFVARS_FILENAME="-"
            TFVARS_COMMAND_PARAM=""
        else
            # pre-configured tfvars
            echo -e "${YC} >>> TFVARS filename '${RC}${PROJECT_TFVAR}${YC}' was found in alias config${NC}"
            TFVARS_FILENAME="$( askIfNotExistsTfVarsFile "${PROJECT_TFVAR}" )"
            TFVARS_COMMAND_PARAM="-var-file=${TFVARS_FILENAME}"
        fi

        # TF plan
        echo -e "\n------------------------------------------------------------------------\n"
        echo -e "${YC} >>> Building TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvars ${RC}${TFVARS_FILENAME}${NC}"
        echo -e "\n------------------------------------------------------------------------\n"
        runTerraform terraform plan ${TFVARS_COMMAND_PARAM} -out=${TF_PLAN_FILENAME}
        echo -e "\n${YC} >>> TF plan:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC} / tfvars ${RC}${TFVARS_FILENAME}${NC}: was generated plan ${RC}${TF_PLAN_FILENAME}${NC}\n${YC} >>> ${NC}(${TF_PLAN_FILE})\n"
        exit;;

    'apply')
        runTerraformInit

        # TF workspaces
        selectWorkspace

        # check TF plan
        if [ ! -f "${TF_PLAN_FILE}" ]; then
            echo -e "${RC}Error${NC}: TF plan file ${YC}${TF_PLAN_FILE}${NC} does not exists. \nPlease build TF plan first"
            exit 10
        fi

        # TF apply
        echo -e "\n------------------------------------------------------------------------\n"
        echo -e "${YC} >>> Applying TF plan:${NC} ${RC}${TF_PLAN_FILENAME}${NC} / alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
        echo -e "${YC} >>> ${NC}File ${YC}${TF_PLAN_FILE}${NC} was modified ${YC}$( humanTimeSinceFileModified "${TF_PLAN_FILE}" ) ago${NC}"
        echo -e "\n------------------------------------------------------------------------\n"
        
        read -p "Are you sure that you want to apply ${CURRENT_WORKSPACE}? To approve print 'yes': " APPLY_APPROVE
        if [ ! "${APPLY_APPROVE}" = 'yes' ]; then
            echo -e "${YC} >>> Exiting ... ${NC}\n"
            exit 0
        fi

        runTerraform terraform apply ${TF_PLAN_FILENAME}
        rm ${TF_PLAN_FILE}

        echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
        echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
        exit;;

    # TODO re-use apply action
    'apply-debug')
        echo -e "${YC} >>> Running in ${RC}DEBUG${YC} mode (without init backend, format check and validation)!${NC}"
        echo -e "\n------------------------------------------------------------------------\n"

        # TF workspaces
        selectWorkspace

        # check TF plan
        if [ ! -f "${TF_PLAN_FILE}" ]; then
            echo -e "${RC}Error${NC}: TF plan file ${YC}${TF_PLAN_FILE}${NC} does not exists. \nPlease build TF plan first"
            exit 10
        fi

        # TF apply
        echo -e "\n------------------------------------------------------------------------\n"
        echo -e "${YC} >>> Applying TF plan:${NC} ${RC}${TF_PLAN_FILENAME}${NC} / alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}"
        echo -e "${YC} >>> ${NC}File ${YC}${TF_PLAN_FILE}${NC} was modified ${YC}$( humanTimeSinceFileModified "${TF_PLAN_FILE}" ) ago${NC}"
        echo -e "\n------------------------------------------------------------------------\n"

        read -p "Are you sure that you want to apply ${CURRENT_WORKSPACE}? To approve print 'yes': " APPLY_APPROVE
        if [ ! "${APPLY_APPROVE}" = 'yes' ]; then
            echo -e "${YC} >>> Exiting ... ${NC}\n"
            exit 0
        fi

        runTerraform terraform apply ${TF_PLAN_FILENAME}
        rm ${TF_PLAN_FILE}

        echo -e "\n${YC} >>> TF apply:${NC} alias ${YC}${ALIAS}${NC} / workspace ${RC}${CURRENT_WORKSPACE}${NC}: applied plan ${RC}${TF_PLAN_FILENAME}${NC}"
        echo -e "${YC} >>> ${NC}Plan ${YC}${TF_PLAN_FILE}${NC} has been ${RC}removed${NC}\n"
        exit;;

    *)
        echo -e "${RC}Error:${NC} ooops, catch all for invalid action ${ACTION}"
        exit 1;;
esac

if [ -n "${PROJECT_HOOK_AFTER_ACTION}" ]; then
    echo -e "${YC} >>> Running hook after action ... ${NC}"
    bash -c "${PROJECT_HOOK_AFTER_ACTION}"
    echo -e "${YC} >>> Done ${NC}"
fi
